/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Pc
 */
public class RajaSweets extends javax.swing.JFrame {

    /**
     * Creates new form Ananya
     */
    public RajaSweets() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        Cart = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        CartItem = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        It2 = new javax.swing.JLabel();
        It1 = new javax.swing.JLabel();
        It3 = new javax.swing.JLabel();
        It5 = new javax.swing.JLabel();
        It4 = new javax.swing.JLabel();
        R1 = new javax.swing.JLabel();
        R2 = new javax.swing.JLabel();
        R3 = new javax.swing.JLabel();
        R4 = new javax.swing.JLabel();
        R5 = new javax.swing.JLabel();
        GrandTotal = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        Totalrs = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        CheckOut = new javax.swing.JButton();
        jPanel31 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jPanel32 = new javax.swing.JPanel();
        jLabel350 = new javax.swing.JLabel();
        jLabel351 = new javax.swing.JLabel();
        jLabel352 = new javax.swing.JLabel();
        jLabel353 = new javax.swing.JLabel();
        jLabel354 = new javax.swing.JLabel();
        jLabel355 = new javax.swing.JLabel();
        jLabel356 = new javax.swing.JLabel();
        jLabel357 = new javax.swing.JLabel();
        jLabel358 = new javax.swing.JLabel();
        jLabel359 = new javax.swing.JLabel();
        jLabel360 = new javax.swing.JLabel();
        jLabel361 = new javax.swing.JLabel();
        jLabel362 = new javax.swing.JLabel();
        jLabel363 = new javax.swing.JLabel();
        jLabel364 = new javax.swing.JLabel();
        jLabel365 = new javax.swing.JLabel();
        jLabel366 = new javax.swing.JLabel();
        jLabel367 = new javax.swing.JLabel();
        jLabel368 = new javax.swing.JLabel();
        jLabel369 = new javax.swing.JLabel();
        jLabel370 = new javax.swing.JLabel();
        jLabel371 = new javax.swing.JLabel();
        jLabel372 = new javax.swing.JLabel();
        jLabel373 = new javax.swing.JLabel();
        jLabel374 = new javax.swing.JLabel();
        Max13 = new javax.swing.JLabel();
        Max = new javax.swing.JLabel();
        jPanel33 = new javax.swing.JPanel();
        jLabel375 = new javax.swing.JLabel();
        It6 = new javax.swing.JLabel();
        It7 = new javax.swing.JLabel();
        It8 = new javax.swing.JLabel();
        It9 = new javax.swing.JLabel();
        It10 = new javax.swing.JLabel();
        R6 = new javax.swing.JLabel();
        R7 = new javax.swing.JLabel();
        R8 = new javax.swing.JLabel();
        R9 = new javax.swing.JLabel();
        R10 = new javax.swing.JLabel();
        GrandTotal1 = new javax.swing.JLabel();
        jLabel376 = new javax.swing.JLabel();
        Totalrs1 = new javax.swing.JLabel();
        jLabel377 = new javax.swing.JLabel();
        CheckOut1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 204));

        jPanel14.setBackground(new java.awt.Color(247, 247, 247));

        jPanel15.setBackground(new java.awt.Color(102, 255, 0));

        jButton1.setBackground(new java.awt.Color(102, 255, 51));
        jButton1.setText("Go Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel53.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        jLabel53.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel53.setText("HotServe");

        jLabel54.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel54.setText("Eat Sleep Repeat");

        Cart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/cart1.png"))); // NOI18N
        Cart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CartMouseClicked(evt);
            }
        });

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/newlogo - Copy.jpeg"))); // NOI18N

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addGap(327, 327, 327)
                        .addComponent(jLabel53))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGap(454, 454, 454)
                        .addComponent(jLabel54)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Cart)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CartItem)
                .addGap(26, 26, 26))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel18))
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel15Layout.createSequentialGroup()
                                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel54))
                            .addGroup(jPanel15Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(Cart))))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(CartItem)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel16.setBackground(new java.awt.Color(255, 255, 204));
        jPanel16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel19.setText("WELCOME TO RAJA SWEETS");

        jLabel1.setText("NEAR MODI MANDIR , MODINAGAR(GHAZIABAD)");

        jLabel2.setText("Minimum Cost Must be Rs.200");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/4.jpg"))); // NOI18N

        jLabel17.setText("Maximum you can select only 5 items at a time");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 747, Short.MAX_VALUE)
                        .addGap(227, 227, 227))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel3)
                .addGap(29, 29, 29))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel24.setBackground(new java.awt.Color(255, 255, 204));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setText("Items selected");

        R1.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N

        R2.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N

        R3.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N

        R4.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N

        R5.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N

        GrandTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        Totalrs.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("CALCULATE TOTAL");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel21))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(It1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                                .addComponent(R1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(It2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(R2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(It3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(R3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(It5, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(GrandTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(It4, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(R4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(R5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel25))))))
                .addGap(153, 153, 153))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Totalrs, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(167, 167, 167))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R1)
                    .addComponent(It1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(It2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(R2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(It3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(R3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(It4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(R4, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(It5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(R5))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(GrandTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Totalrs, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                        .addGap(20, 20, 20))))
        );

        CheckOut.setBackground(new java.awt.Color(102, 255, 0));
        CheckOut.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        CheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckOutActionPerformed(evt);
            }
        });

        jPanel31.setBackground(new java.awt.Color(255, 255, 204));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel20.setText("FOOD MENU");

        jLabel350.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel350.setText("VEG :");

        jLabel351.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel351.setText("* AALU PRATHA");

        jLabel352.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel352.setText("* PANEER PRATHA");

        jLabel353.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel353.setText("* BUTTER NAN");

        jLabel354.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel354.setText("* CHHOLE BHATURE");

        jLabel355.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel355.setText("* CHILLI POTATO");

        jLabel356.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel356.setText("* MALAI  KOFTA");

        jLabel357.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel357.setText("* PALAK PANEER");

        jLabel358.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel358.setText("* BREAD PIZZA");

        jLabel359.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel359.setText("RS. 50");

        jLabel360.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel360.setText("RS. 50");

        jLabel361.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel361.setText("RS. 30");

        jLabel362.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel362.setText("RS. 40 ");

        jLabel363.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel363.setText("RS. 70");

        jLabel364.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel364.setText("RS. 100");

        jLabel365.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel365.setText("RS. 80");

        jLabel366.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel366.setText("RS. 30");

        jLabel367.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel367.setForeground(new java.awt.Color(51, 153, 0));
        jLabel367.setText("Add to Cart");
        jLabel367.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel367MouseClicked(evt);
            }
        });

        jLabel368.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel368.setForeground(new java.awt.Color(51, 153, 0));
        jLabel368.setText("Add to Cart");
        jLabel368.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel368MouseClicked(evt);
            }
        });

        jLabel369.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel369.setForeground(new java.awt.Color(51, 153, 0));
        jLabel369.setText("Add to Cart");
        jLabel369.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel369MouseClicked(evt);
            }
        });

        jLabel370.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel370.setForeground(new java.awt.Color(51, 153, 0));
        jLabel370.setText("Add to Cart");
        jLabel370.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel370MouseClicked(evt);
            }
        });

        jLabel371.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel371.setForeground(new java.awt.Color(51, 153, 0));
        jLabel371.setText("Add to Cart");
        jLabel371.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel371MouseClicked(evt);
            }
        });

        jLabel372.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel372.setForeground(new java.awt.Color(51, 153, 0));
        jLabel372.setText("Add to Cart");
        jLabel372.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel372MouseClicked(evt);
            }
        });

        jLabel373.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel373.setForeground(new java.awt.Color(51, 153, 0));
        jLabel373.setText("Add to Cart");
        jLabel373.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel373MouseClicked(evt);
            }
        });

        jLabel374.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel374.setForeground(new java.awt.Color(51, 153, 0));
        jLabel374.setText("Add to Cart");
        jLabel374.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel374MouseClicked(evt);
            }
        });

        Max13.setForeground(new java.awt.Color(255, 51, 51));

        Max.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel32Layout = new javax.swing.GroupLayout(jPanel32);
        jPanel32.setLayout(jPanel32Layout);
        jPanel32Layout.setHorizontalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel32Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel350, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(Max13, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel32Layout.createSequentialGroup()
                .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel32Layout.createSequentialGroup()
                        .addContainerGap(292, Short.MAX_VALUE)
                        .addComponent(Max))
                    .addGroup(jPanel32Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel32Layout.createSequentialGroup()
                                    .addComponent(jLabel353)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel361, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel32Layout.createSequentialGroup()
                                    .addComponent(jLabel351)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel360, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel32Layout.createSequentialGroup()
                                    .addComponent(jLabel358)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel366, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel32Layout.createSequentialGroup()
                                    .addComponent(jLabel354)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel362, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel32Layout.createSequentialGroup()
                                    .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel357)
                                        .addComponent(jLabel355))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel363, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel364, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel32Layout.createSequentialGroup()
                                    .addComponent(jLabel356)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel365, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel32Layout.createSequentialGroup()
                                .addComponent(jLabel352, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(89, 89, 89)
                                .addComponent(jLabel359, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(30, 30, 30)
                .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel367)
                    .addComponent(jLabel368)
                    .addComponent(jLabel369)
                    .addComponent(jLabel370)
                    .addComponent(jLabel371)
                    .addComponent(jLabel372)
                    .addComponent(jLabel373)
                    .addComponent(jLabel374))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel32Layout.setVerticalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel32Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel350)
                    .addComponent(Max13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Max)
                .addGap(7, 7, 7)
                .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel352, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel359)
                    .addComponent(jLabel367))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel32Layout.createSequentialGroup()
                        .addComponent(jLabel351, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel353, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel361)
                            .addComponent(jLabel369))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel354, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel362)
                            .addComponent(jLabel370)))
                    .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel360)
                        .addComponent(jLabel368)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel32Layout.createSequentialGroup()
                        .addComponent(jLabel355, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel357, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel364)
                            .addComponent(jLabel372))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel356, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel365)
                            .addComponent(jLabel374)))
                    .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel363)
                        .addComponent(jLabel371)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel358, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel366)
                    .addComponent(jLabel373))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel375.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel375.setText("Items selected");

        R6.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N

        R7.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N

        R8.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N

        R9.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N

        R10.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N

        GrandTotal1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel376.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        Totalrs1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel377.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel377.setText("CALCULATE TOTAL");
        jLabel377.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel377MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel33Layout = new javax.swing.GroupLayout(jPanel33);
        jPanel33.setLayout(jPanel33Layout);
        jPanel33Layout.setHorizontalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel33Layout.createSequentialGroup()
                .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel33Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel375))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel33Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel33Layout.createSequentialGroup()
                                .addComponent(It7, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                                .addComponent(R6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel33Layout.createSequentialGroup()
                                .addComponent(It6, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(R7, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel33Layout.createSequentialGroup()
                                .addComponent(It8, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(R8, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel33Layout.createSequentialGroup()
                                .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(It9, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(GrandTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(It10, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel377))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(R9, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(R10, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel376))))))
                .addGap(153, 153, 153))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel33Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Totalrs1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(167, 167, 167))
        );
        jPanel33Layout.setVerticalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel33Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel375)
                .addGap(27, 27, 27)
                .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R6)
                    .addComponent(It7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(It6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(R7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(It8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(R8))
                .addGap(18, 18, 18)
                .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(It10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(R9, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(It9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(R10))
                .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel33Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel376, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel33Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel377)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(GrandTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Totalrs1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20))))
        );

        CheckOut1.setBackground(new java.awt.Color(102, 255, 0));
        CheckOut1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        CheckOut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckOut1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel31Layout = new javax.swing.GroupLayout(jPanel31);
        jPanel31.setLayout(jPanel31Layout);
        jPanel31Layout.setHorizontalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel31Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jPanel32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel31Layout.createSequentialGroup()
                .addContainerGap(520, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addGap(241, 241, 241)
                .addComponent(CheckOut1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel31Layout.setVerticalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel31Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckOut1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel31Layout.createSequentialGroup()
                        .addComponent(jPanel32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 11, Short.MAX_VALUE))
                    .addComponent(jPanel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
            .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel24Layout.createSequentialGroup()
                    .addGap(28, 28, 28)
                    .addComponent(jPanel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(28, 28, 28)))
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 44, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel24Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 HomePage h=new HomePage();
        h.setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CartMouseClicked

    }//GEN-LAST:event_CartMouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        //@LAKSHAY(RA1711003030064)

        if(iii==1)
        {
            a=Integer.valueOf(R1.getText());
            b=0;
            c=0;
            d=0;
            e=0;
        }
        else if(iii==2)
        {
            a=Integer.valueOf(R1.getText());

            b=Integer.valueOf(R2.getText());
            c=0;d=0;e=0;
        }

        else if(iii==3)
        {
            a=Integer.valueOf(R1.getText());

            b=Integer.valueOf(R2.getText());
            c=Integer.valueOf(R3.getText());
            d=0;
            e=0;

        }
        else if(iii==4)
        {
            a=Integer.valueOf(R1.getText());

            b=Integer.valueOf(R2.getText());
            c=Integer.valueOf(R3.getText());
            e=0;
            d=Integer.valueOf(R4.getText());
        }
        //c=Integer.valueOf(R3.getText());
        //d=Integer.valueOf(R4.getText());
        //e=Integer.valueOf(R5.getText());
        else if(iii==5)
        {
            a=Integer.valueOf(R1.getText());

            b=Integer.valueOf(R2.getText());
            c=Integer.valueOf(R3.getText());
            e=Integer.valueOf(R5.getText());
            d=Integer.valueOf(R4.getText());

        }
        int f=a+b+c+d+e;
        if(f>=100)
        {
            CheckOut.setText("PROCEED TO CHECKOUT");
        }
        if(f<100)
        {
            Max.setText("Order value must be above 100");
        }
        else
        {
            String s=Integer.toString(f);
            GrandTotal.setText("GRAND TOTAL");
            Totalrs.setText(s);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel16MouseClicked

    private void CheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckOutActionPerformed
        Payment h=new Payment();
        h.setVisible(true);
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_CheckOutActionPerformed

    private void jLabel367MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel367MouseClicked

        //Cart c=new Cart();
        //c.setItem();
        //@LAKSHAY(RA1711003030064)
        Max.setText("");
        iii=iii+1;
        if(iii==1)
        {
            CartItem.setText("1");
            It1.setText("PANEER PRATHA");//if (i1.equals(""))
            R1.setText("50");
        }
        else  if(iii==2)
        {
            CartItem.setText("2");
            It2.setText("PANEER PRATHA");//if (i1.equals(""))
            R2.setText("50");
        }
        else  if(iii==3)
        {
            CartItem.setText("3");
            It3.setText("PANEER PRATHA");//if (i1.equals(""))
            R3.setText("50");
        }
        else  if(iii==4)
        {
            CartItem.setText("4");
            It4.setText("PANEER PRATHA");//if (i1.equals(""))
            R4.setText("50");
        }
        else  if(iii==5)
        {
            CartItem.setText("5");
            R5.setText("50");
            It5.setText("PANEER PRATHA");//if (i1.equals(""))
        }
        else
        {
            Max.setText("*Sorry You cannot add more than 5 Items");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel367MouseClicked

    private void jLabel368MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel368MouseClicked
        //@LAKSHAY(RA1711003030064)
        Max.setText("");
        iii=iii+1;
        if(iii==1)
        {
            CartItem.setText("1");
            It1.setText("AALU PRATHA");//if (i1.equals(""))
            R1.setText("50");
        }
        else  if(iii==2)
        {
            CartItem.setText("2");
            It2.setText("AALU PRATHA");//if (i1.equals(""))
            R2.setText("50");
        }
        else  if(iii==3)
        {
            CartItem.setText("3");
            It3.setText("AALU PRATHA");//if (i1.equals(""))
            R3.setText("50");
        }
        else  if(iii==4)
        {
            CartItem.setText("4");
            It4.setText("AALU PRATHA");//if (i1.equals(""))
            R4.setText("50");
        }
        else  if(iii==5)
        {
            CartItem.setText("5");
            R5.setText("50");
            It5.setText("AALU PRATHA");//if (i1.equals(""))
        }
        else
        {
            Max.setText("*Sorry You cannot add more than 5 Items");
        }
    }//GEN-LAST:event_jLabel368MouseClicked

    private void jLabel369MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel369MouseClicked
        //@LAKSHAY(RA1711003030064)
        Max.setText("");
        iii=iii+1;
        if(iii==1)
        {
            CartItem.setText("1");
            It1.setText("BUTTER NAN");//if (i1.equals(""))
            R1.setText("30");
        }
        else  if(iii==2)
        {
            CartItem.setText("2");
            It2.setText("BUTTER NAN");//if (i1.equals(""))
            R2.setText("30");
        }
        else  if(iii==3)
        {
            CartItem.setText("3");
            It3.setText("BUTTER NAN");//if (i1.equals(""))
            R3.setText("30");
        }
        else  if(iii==4)
        {
            CartItem.setText("4");
            It4.setText("BUTTER NAN");//if (i1.equals(""))
            R4.setText("30");
        }
        else  if(iii==5)
        {
            CartItem.setText("5");
            R5.setText("30");
            It5.setText("BUTTER NAN");//if (i1.equals(""))
        }
        else
        {
            Max.setText("*Sorry You cannot add more than 5 Items");
        }
    }//GEN-LAST:event_jLabel369MouseClicked

    private void jLabel370MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel370MouseClicked
        //@LAKSHAY(RA1711003030064)
        Max.setText("");
        iii=iii+1;
        if(iii==1)
        {
            CartItem.setText("1");
            It1.setText("CHHOLE BHATURE");//if (i1.equals(""))
            R1.setText("40");
        }
        else  if(iii==2)
        {
            CartItem.setText("2");
            It2.setText("CHHOLE BHATURE");//if (i1.equals(""))
            R2.setText("40");
        }
        else  if(iii==3)
        {
            CartItem.setText("3");
            It3.setText("CHHOLE BHATURE");//if (i1.equals(""))
            R3.setText("40");
        }
        else  if(iii==4)
        {
            CartItem.setText("4");
            It4.setText("CHHOLE BHATURE");//if (i1.equals(""))
            R4.setText("40");
        }
        else  if(iii==5)
        {
            CartItem.setText("5");
            R5.setText("40");
            It5.setText("CHHOLE BHATURE");//if (i1.equals(""))
        }
        else
        {
            Max.setText("*Sorry You cannot add more than 5 Items");
        }
    }//GEN-LAST:event_jLabel370MouseClicked

    private void jLabel371MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel371MouseClicked
        //@LAKSHAY(RA1711003030064)
        Max.setText("");
        iii=iii+1;
        if(iii==1)
        {
            CartItem.setText("1");
            It1.setText("CHILLI POTATO");//if (i1.equals(""))
            R1.setText("70");
        }
        else  if(iii==2)
        {
            CartItem.setText("2");
            It2.setText("CHILLI POTATO");//if (i1.equals(""))
            R2.setText("70");
        }
        else  if(iii==3)
        {
            CartItem.setText("3");
            It3.setText("CHILLI POTATO");//if (i1.equals(""))
            R3.setText("70");
        }
        else  if(iii==4)
        {
            CartItem.setText("4");
            It4.setText("CHILLI POTATO");//if (i1.equals(""))
            R4.setText("70");
        }
        else  if(iii==5)
        {
            CartItem.setText("5");
            R5.setText("70");
            It5.setText("CHILLI POTATO");//if (i1.equals(""))
        }
        else
        {
            Max.setText("*Sorry You cannot add more than 5 Items");
        }
    }//GEN-LAST:event_jLabel371MouseClicked

    private void jLabel372MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel372MouseClicked
        //@LAKSHAY(RA1711003030064)
        Max.setText("");
        iii=iii+1;
        if(iii==1)
        {
            CartItem.setText("1");
            It1.setText("PALAK PANEER");//if (i1.equals(""))
            R1.setText("100");
        }
        else  if(iii==2)
        {
            CartItem.setText("2");
            It2.setText("PALAK PANEER");//if (i1.equals(""))
            R2.setText("100");
        }
        else  if(iii==3)
        {
            CartItem.setText("3");
            It3.setText("PALAK PANEER");//if (i1.equals(""))
            R3.setText("100");
        }
        else  if(iii==4)
        {
            CartItem.setText("4");
            It4.setText("PALAK PANEER");//if (i1.equals(""))
            R4.setText("100");
        }
        else  if(iii==5)
        {
            CartItem.setText("5");
            R5.setText("100");
            It5.setText("PALAK PANEER");//if (i1.equals(""))
        }
        else
        {
            Max.setText("*Sorry You cannot add more than 5 Items");
        }
    }//GEN-LAST:event_jLabel372MouseClicked

    private void jLabel373MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel373MouseClicked
        //@LAKSHAY(RA1711003030064)
        Max.setText("");
        iii=iii+1;
        if(iii==1)
        {
            CartItem.setText("1");
            It1.setText("BREAD PIZZA");//if (i1.equals(""))
            R1.setText("30");
        }
        else  if(iii==2)
        {
            CartItem.setText("2");
            It2.setText("BREAD PIZZA");//if (i1.equals(""))
            R2.setText("30");
        }
        else  if(iii==3)
        {
            CartItem.setText("3");
            It3.setText("BREAD PIZZA");//if (i1.equals(""))
            R3.setText("30");
        }
        else  if(iii==4)
        {
            CartItem.setText("4");
            It4.setText("BREAD PIZZA");//if (i1.equals(""))
            R4.setText("30");
        }
        else  if(iii==5)
        {
            CartItem.setText("5");
            R5.setText("30");
            It5.setText("BREAD PIZZA");//if (i1.equals(""))
        }
        else
        {
            Max.setText("*Sorry You cannot add more than 5 Items");
        }
    }//GEN-LAST:event_jLabel373MouseClicked

    private void jLabel374MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel374MouseClicked
        //@LAKSHAY(RA1711003030064)
        Max.setText("");
        iii=iii+1;
        if(iii==1)
        {
            CartItem.setText("1");
            It1.setText("MALAI KOFTA");//if (i1.equals(""))
            R1.setText("80");
        }
        else  if(iii==2)
        {
            CartItem.setText("2");
            It2.setText("MALAI KOFTA");//if (i1.equals(""))
            R2.setText("80");
        }
        else  if(iii==3)
        {
            CartItem.setText("3");
            It3.setText("MALAI KOFTA");//if (i1.equals(""))
            R3.setText("80");
        }
        else  if(iii==4)
        {
            CartItem.setText("4");
            It4.setText("MALAI KOFTA");//if (i1.equals(""))
            R4.setText("80");
        }
        else  if(iii==5)
        {
            CartItem.setText("5");
            R5.setText("80");
            It5.setText("MALAI KOFTA");//if (i1.equals(""))
        }
        else
        {
            Max.setText("*Sorry You cannot add more than 5 Items");
        }
    }//GEN-LAST:event_jLabel374MouseClicked

    private void jLabel377MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel377MouseClicked
        //@LAKSHAY(RA1711003030064)

        if(iii==1)
        {
            a=Integer.valueOf(R1.getText());
            b=0;
            c=0;
            d=0;
            e=0;
        }
        else if(iii==2)
        {
            a=Integer.valueOf(R1.getText());

            b=Integer.valueOf(R2.getText());
            c=0;d=0;e=0;
        }

        else if(iii==3)
        {
            a=Integer.valueOf(R1.getText());

            b=Integer.valueOf(R2.getText());
            c=Integer.valueOf(R3.getText());
            d=0;
            e=0;

        }
        else if(iii==4)
        {
            a=Integer.valueOf(R1.getText());

            b=Integer.valueOf(R2.getText());
            c=Integer.valueOf(R3.getText());
            e=0;
            d=Integer.valueOf(R4.getText());
        }
        //c=Integer.valueOf(R3.getText());
        //d=Integer.valueOf(R4.getText());
        //e=Integer.valueOf(R5.getText());
        else if(iii==5)
        {
            a=Integer.valueOf(R1.getText());

            b=Integer.valueOf(R2.getText());
            c=Integer.valueOf(R3.getText());
            e=Integer.valueOf(R5.getText());
            d=Integer.valueOf(R4.getText());

        }
        int f=a+b+c+d+e;
        if(f>=100)
        {
            CheckOut.setText("PROCEED TO CHECKOUT");
        }
        if(f<100)
        {
            Max.setText("Order value must be above 100");
        }
        else
        {
            String s=Integer.toString(f);
            GrandTotal.setText("GRAND TOTAL");
            Totalrs.setText(s);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel377MouseClicked

    private void CheckOut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckOut1ActionPerformed
        Payment h=new Payment();
        h.setVisible(true);
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_CheckOut1ActionPerformed
static int iii=0;
int a,b,c,d,e;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RajaSweets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RajaSweets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RajaSweets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RajaSweets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RajaSweets().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cart;
    private javax.swing.JLabel CartItem;
    private javax.swing.JButton CheckOut;
    private javax.swing.JButton CheckOut1;
    private javax.swing.JLabel GrandTotal;
    private javax.swing.JLabel GrandTotal1;
    private javax.swing.JLabel It1;
    private javax.swing.JLabel It10;
    private javax.swing.JLabel It2;
    private javax.swing.JLabel It3;
    private javax.swing.JLabel It4;
    private javax.swing.JLabel It5;
    private javax.swing.JLabel It6;
    private javax.swing.JLabel It7;
    private javax.swing.JLabel It8;
    private javax.swing.JLabel It9;
    private javax.swing.JLabel Max;
    private javax.swing.JLabel Max11;
    private javax.swing.JLabel Max12;
    private javax.swing.JLabel Max13;
    private javax.swing.JLabel Max3;
    private javax.swing.JLabel R1;
    private javax.swing.JLabel R10;
    private javax.swing.JLabel R2;
    private javax.swing.JLabel R3;
    private javax.swing.JLabel R4;
    private javax.swing.JLabel R5;
    private javax.swing.JLabel R6;
    private javax.swing.JLabel R7;
    private javax.swing.JLabel R8;
    private javax.swing.JLabel R9;
    private javax.swing.JLabel Totalrs;
    private javax.swing.JLabel Totalrs1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel110;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel114;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JLabel jLabel116;
    private javax.swing.JLabel jLabel117;
    private javax.swing.JLabel jLabel118;
    private javax.swing.JLabel jLabel119;
    private javax.swing.JLabel jLabel120;
    private javax.swing.JLabel jLabel121;
    private javax.swing.JLabel jLabel122;
    private javax.swing.JLabel jLabel123;
    private javax.swing.JLabel jLabel124;
    private javax.swing.JLabel jLabel125;
    private javax.swing.JLabel jLabel126;
    private javax.swing.JLabel jLabel127;
    private javax.swing.JLabel jLabel128;
    private javax.swing.JLabel jLabel129;
    private javax.swing.JLabel jLabel130;
    private javax.swing.JLabel jLabel131;
    private javax.swing.JLabel jLabel132;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel298;
    private javax.swing.JLabel jLabel299;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel300;
    private javax.swing.JLabel jLabel301;
    private javax.swing.JLabel jLabel302;
    private javax.swing.JLabel jLabel303;
    private javax.swing.JLabel jLabel304;
    private javax.swing.JLabel jLabel305;
    private javax.swing.JLabel jLabel306;
    private javax.swing.JLabel jLabel307;
    private javax.swing.JLabel jLabel308;
    private javax.swing.JLabel jLabel309;
    private javax.swing.JLabel jLabel310;
    private javax.swing.JLabel jLabel311;
    private javax.swing.JLabel jLabel312;
    private javax.swing.JLabel jLabel313;
    private javax.swing.JLabel jLabel314;
    private javax.swing.JLabel jLabel315;
    private javax.swing.JLabel jLabel316;
    private javax.swing.JLabel jLabel317;
    private javax.swing.JLabel jLabel318;
    private javax.swing.JLabel jLabel319;
    private javax.swing.JLabel jLabel320;
    private javax.swing.JLabel jLabel321;
    private javax.swing.JLabel jLabel322;
    private javax.swing.JLabel jLabel323;
    private javax.swing.JLabel jLabel324;
    private javax.swing.JLabel jLabel325;
    private javax.swing.JLabel jLabel326;
    private javax.swing.JLabel jLabel327;
    private javax.swing.JLabel jLabel328;
    private javax.swing.JLabel jLabel329;
    private javax.swing.JLabel jLabel330;
    private javax.swing.JLabel jLabel331;
    private javax.swing.JLabel jLabel332;
    private javax.swing.JLabel jLabel333;
    private javax.swing.JLabel jLabel334;
    private javax.swing.JLabel jLabel335;
    private javax.swing.JLabel jLabel336;
    private javax.swing.JLabel jLabel337;
    private javax.swing.JLabel jLabel338;
    private javax.swing.JLabel jLabel339;
    private javax.swing.JLabel jLabel340;
    private javax.swing.JLabel jLabel341;
    private javax.swing.JLabel jLabel342;
    private javax.swing.JLabel jLabel343;
    private javax.swing.JLabel jLabel344;
    private javax.swing.JLabel jLabel345;
    private javax.swing.JLabel jLabel346;
    private javax.swing.JLabel jLabel347;
    private javax.swing.JLabel jLabel348;
    private javax.swing.JLabel jLabel349;
    private javax.swing.JLabel jLabel350;
    private javax.swing.JLabel jLabel351;
    private javax.swing.JLabel jLabel352;
    private javax.swing.JLabel jLabel353;
    private javax.swing.JLabel jLabel354;
    private javax.swing.JLabel jLabel355;
    private javax.swing.JLabel jLabel356;
    private javax.swing.JLabel jLabel357;
    private javax.swing.JLabel jLabel358;
    private javax.swing.JLabel jLabel359;
    private javax.swing.JLabel jLabel360;
    private javax.swing.JLabel jLabel361;
    private javax.swing.JLabel jLabel362;
    private javax.swing.JLabel jLabel363;
    private javax.swing.JLabel jLabel364;
    private javax.swing.JLabel jLabel365;
    private javax.swing.JLabel jLabel366;
    private javax.swing.JLabel jLabel367;
    private javax.swing.JLabel jLabel368;
    private javax.swing.JLabel jLabel369;
    private javax.swing.JLabel jLabel370;
    private javax.swing.JLabel jLabel371;
    private javax.swing.JLabel jLabel372;
    private javax.swing.JLabel jLabel373;
    private javax.swing.JLabel jLabel374;
    private javax.swing.JLabel jLabel375;
    private javax.swing.JLabel jLabel376;
    private javax.swing.JLabel jLabel377;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
